apiVersion: configsync.gke.io/v1beta1
kind: RootSync

metadata:
  name: config-sync-demo
  namespace: config-management-system # RootSync must be in this namespace

spec:
  sourceFormat: unstructured
  git:
    repo: github.com/aravind254/testConfigSync.git
    dir: /root
    branch: main
    auth: none
